insert into contrato (id_contrato, id_cliente, estado, fecha_contrato, precio_contrato) values (1, 1, 'Oculoglandular tularemia', '2021-09-28', '€51,70');
insert into contrato (id_contrato, id_cliente, estado, fecha_contrato, precio_contrato) values (2, 2, 'W/crft fall NEC-pers NOS', '2021-08-19', '€17,94');
insert into contrato (id_contrato, id_cliente, estado, fecha_contrato, precio_contrato) values (3, 3, 'Tubrcloma brain-micro dx', '2021-09-15', '€26,01');
insert into contrato (id_contrato, id_cliente, estado, fecha_contrato, precio_contrato) values (4, 4, 'Dengue', '2022-06-02', '€69,48');
insert into contrato (id_contrato, id_cliente, estado, fecha_contrato, precio_contrato) values (5, 5, 'Neurohypophysis dis NEC', '2021-03-19', '€0,34');
insert into contrato (id_contrato, id_cliente, estado, fecha_contrato, precio_contrato) values (6, 6, 'Ear anom NOS/impair hear', '2021-05-15', '€53,00');
insert into contrato (id_contrato, id_cliente, estado, fecha_contrato, precio_contrato) values (7, 7, 'Screen-cong hip dislocat', '2021-09-17', '€51,12');
insert into contrato (id_contrato, id_cliente, estado, fecha_contrato, precio_contrato) values (8, 8, 'Vascular anom post eye', '2021-11-07', '€67,39');
insert into contrato (id_contrato, id_cliente, estado, fecha_contrato, precio_contrato) values (9, 9, 'Lt-for-date w/mal <500g', '2021-04-16', '€20,64');
insert into contrato (id_contrato, id_cliente, estado, fecha_contrato, precio_contrato) values (10, 10, 'Chr osteomyelit-up/arm', '2022-01-16', '€63,15');
